# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
use_frameworks!
target 'SuperTicket' do
pod 'SnapKit', '~> 0.20.0'
pod 'ChameleonFramework/Swift'
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'AVOSCloudCrashReporting'
pod 'NVActivityIndicatorView'
pod 'DZNEmptyDataSet'
pod 'ImagePicker'
pod 'Kingfisher', '~> 2.2'
pod "PagingMenuController"
end

